package dk.aau.portal.mkr.qa.internal;

import java.util.List;

import dk.aau.portal.mkr.qa.Question;

public interface QuestionRepository {

	public Question findQuestion(int id);
	public List<Question> getAll(); 
	public void update(Question question);
	public void destroy(Question question);
	/**
	 * 
	 * @param question can be an existing question, this would yield a clone.
	 * @return the autogenerated id 
	 */
	public int create(Question question);
	
}
